CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  username TEXT UNIQUE NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  age INTEGER NOT NULL,
  gender INTEGER NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role INTEGER,
  avatar TEXT,
  registered DATETIME NOT NULL
);