CREATE TABLE chats (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  user1_id INTEGER NOT NULL,
  user2_id INTEGER NOT NULL,
  FOREIGN KEY(user1_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(user2_id) REFERENCES users(id) ON DELETE CASCADE
);